WinegramAnalisisBundle\Domain\Entity\Comment:
    type: entity
    table: comment
    repositoryClass: WinegramAnalisisBundle\Domain\Repository\CommentRepository
    id:
        id:
            type: string
            id: true
    fields:
        originalText:
            type: string
            length: 100
        likes_count:
            type: string
            nullable: true
        username:
            type: string
            nullable: true
        type:
            type: string
            nullable: true
        idRedis:
            type: string
            nullable: true
        media:
            type: string
            nullable: true
        search_id:
            type: string
            nullable: true
        search_content:
            type: string
            nullable: true
        query:
            type: string
            nullable: true
        lang:
            type: string
            nullable: true
        englishText:
            type: string
            nullable: true
        textSentiment:
            type: string
            nullable: true
        textTwittSentiment:
            type: string
            nullable: true
        gender:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
