WinegramAnalisisBundle\Domain\Entity\KeyWord:
    type: entity
    table: keyword
    repositoryClass: WinegramAnalisisBundle\Domain\Repository\KeyWordRepository
    id:
        id:
            type: string
            id: true
    fields:
        text:
            type: string
            length: 100
        comment_id:
            type: string
            nullable: false
    lifecycleCallbacks: {  }
